name: Build
on:
  workflow_call:

jobs:
  Appimage:
      name: AppImage
      strategy:
        matrix:
          os: [ubuntu-22.04]
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          shell: bash
      steps:
        - name: Checking out the code
          uses: actions/checkout@v4
          with:
            submodules: 'true'
            fetch-depth: 0

        - name: Install dependencies
          id: vars
          run: |
            sudo apt-get -qq update
            sudo apt-get -qq install libxkbcommon-x11-0 libc6-i386 build-essential libgl1-mesa-dev mesa-common-dev libgles2-mesa-dev libxkbcommon-x11-0 libxcb-icccm4-dev libxcb-xinerama0 libxcb-image0 libxcb-keysyms1 libxcb-* fakeroot
            sudo apt-get -qq install libfuse2
            sudo pip install git-archive-all

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          timeout-minutes: 10
          with:
            version: 6.6.*
            target: desktop
            host: linux
            install-deps: true
            aqtversion: '==3.1.*'

        - name: Generate project
          run: |
            cmake -S . -B build -G "Ninja" -DVERSION=`git describe --always` -DCMAKE_BUILD_TYPE=Release

        - name: Compile and deploy
          run: |
            cmake --build build --target GitQlient -j4
            cmake --build build --target install

        - name: Build AppImage
          run: |
            export VERSION=`git describe --always`
            chmod +x build/install/usr/bin/gitqlient
            wget -q -O linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
            chmod +x linuxdeployqt
            ./linuxdeployqt build/install/usr/share/applications/*.desktop -appimage -no-translations -extra-plugins=iconengines,imageformats
            chmod +x GitQlient-*

        - name: Upload AppImage
          uses: actions/upload-artifact@v4
          with:
            name: appimage
            path: GitQlient-*.AppImage
