name: Master
run-name: Latest master run

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  Clean:
    name: Clean old workflows
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Prune previous runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          keep_minimum_runs: 2
          repository: ${{ github.repository }}
          retain_days: 0

  CancelPrevious:
    name: Cancel previous builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  BuildProject:
    name: Build 🧱
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      actions: write
      contents: write
